# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f400ae8b43690c96450910ac1fb8d70b41de560ed4fd17f0d4d7a842bb8ec0e171675dbac88fa9a427e1a1e0d7cbef470b9a174eed117beb991c4a4ad1b0224

test:
  secret_key_base: 11b4b3d254a4c9862a6ae2235e7e3f35a06783287b197dee77e033c4e13ad5693c50271e78069907b1294d73939f919561286a72c15ad2c576a21cb7f72178f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
